package cl.aiep.examen.dto;
// Generated 05-08-2016 3:01:20 by Hibernate Tools 4.3.1



/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private int horas;
     private int valorHora;

    public Profesor() {
    }

    public Profesor(String nombre, int horas, int valorHora) {
       this.nombre = nombre;
       this.horas = horas;
       this.valorHora = valorHora;
    }
    
     public Profesor(Integer id, String nombre, int horas, int valorHora) {
       this.id = id;
       this.nombre = nombre;
       this.horas = horas;
       this.valorHora = valorHora;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getHoras() {
        return this.horas;
    }
    
    public void setHoras(int horas) {
        this.horas = horas;
    }
    public int getValorHora() {
        return this.valorHora;
    }
    
    public void setValorHora(int valorHora) {
        this.valorHora = valorHora;
    }

    @Override
    public String toString() {
        return "Profesor{" + "id=" + id + ", nombre=" + nombre + ", horas=" + horas + ", valorHora=" + valorHora + '}';
    }

    


}


